# Generated by Django 4.2.7 on 2023-11-17 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_rename_items_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='Category',
            new_name='category',
        ),
    ]
