# Generated by Django 4.2.7 on 2023-12-02 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0007_gender'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gender',
        ),
    ]
