# Generated by Django 4.2.7 on 2023-12-02 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0010_alter_category_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',)},
        ),
    ]
